//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vsan.DataMigration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_source
    {
        public long Id { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Creator { get; set; }
        public System.DateTime ModifyTime { get; set; }
        public string Modifier { get; set; }
        public int State { get; set; }
        public long UserId { get; set; }
        public string DataSourceName { get; set; }
        public string TypeCode { get; set; }
        public string Host { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Link { get; set; }
        public string DbName { get; set; }
        public int Port { get; set; }
        public string TableName { get; set; }
    }
}
