//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vsan.DataMigration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dictionary
    {
        public long Id { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Creator { get; set; }
        public System.DateTime ModifyTime { get; set; }
        public string Modifier { get; set; }
        public int State { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public string KeyCode { get; set; }
        public string ShowText { get; set; }
        public decimal DecimalValue { get; set; }
        public int IntValue { get; set; }
    }
}
