//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vsan.DataMigration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_account
    {
        public long Id { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Creator { get; set; }
        public System.DateTime ModifyTime { get; set; }
        public string Modifier { get; set; }
        public int State { get; set; }
        public string Nickname { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string HeadPortrait { get; set; }
        public string TrueName { get; set; }
        public decimal Balance { get; set; }
        public long Credits { get; set; }
        public int Level { get; set; }
        public long InviterId { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public long EmpiricalValue { get; set; }
    }
}
