//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vsan.DataMigration.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataMigrationEntities : DbContext
    {
        public DataMigrationEntities()
            : base("name=DataMigrationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<data_source> data_source { get; set; }
        public virtual DbSet<data_source_fields> data_source_fields { get; set; }
        public virtual DbSet<dictionary> dictionary { get; set; }
        public virtual DbSet<field_mapping> field_mapping { get; set; }
        public virtual DbSet<field_method_mapping> field_method_mapping { get; set; }
        public virtual DbSet<log> log { get; set; }
        public virtual DbSet<method> method { get; set; }
        public virtual DbSet<permission> permission { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<role_permission_mapping> role_permission_mapping { get; set; }
        public virtual DbSet<user_account> user_account { get; set; }
        public virtual DbSet<user_role_mapping> user_role_mapping { get; set; }
        public virtual DbSet<work_order> work_order { get; set; }
    }
}
