//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vsan.DataMigration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_order
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public string OrderId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Creator { get; set; }
        public System.DateTime ModifyTime { get; set; }
        public string Modifier { get; set; }
        public int State { get; set; }
        public long InportSourceId { get; set; }
        public string ExportSourceName { get; set; }
        public long ExportSourceId { get; set; }
        public string Remake { get; set; }
        public int FieldCount { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public long ElapsedTime { get; set; }
        public string Exception { get; set; }
        public string InportTable { get; set; }
        public string ExportTable { get; set; }
        public long DataCount { get; set; }
        public string InportWhere { get; set; }
        public string InportOrderByField { get; set; }
        public int PageIndex { get; set; }
        public int PageSize { get; set; }
        public string InportSourceName { get; set; }
    }
}
